---
name: Feature
description: Create a Issue Type - Feature
title: "Feature: "
labels:
  - Feature
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the Feature
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain in detail
      placeholder: Explain the Feature description here
    validations:
      required: true
  - type: input
    id: narappname
    attributes:
      label: NAR Application Name
  - type: input
    id: Link
    attributes:
      label: Epic link/Parent link
      placeholder: https://github.com/example/repo/issues/1
  - type: textarea
    id: Components
    attributes:
      label: Components
      description: Explain in detail
      placeholder: Explain the Components description here
