name: Story
description: Create a Issue Type : Story
title: "Story: "
labels: ["story"]

body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the story
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain in detail
      placeholder: Explain the Story description here
    validations:
      required: true

  - type: input
    id: narappname
    attributes:
      label: NAR Application Name
